version: 2

models:
    - name: dim_listings_cleaned
      description: Cleaned table that contains Airbnb listings.
      columns:
        - name: listing_id
          description: Primary key for the listing 
          tests:
            - unique
            - not_null
        - name: host_id
          description: The host's id. References the host table.
          tests:
            - not_null
            - relationships:
                to: ref('dim_hosts_cleaned')
                field: host_id
        - name: room_type
          description: Type of apartment/room.
          tests:
            - accepted_values:
                values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
        - name: minimum_nights
          description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
          tests:
            - positive_value   
    - name: dim_hosts_cleaned
      description: Cleaned table that contains Airbnb hosts.
      columns:
        - name: host_id
          description: Primary key for the host.
          tests:
            - unique
            - not_null
        - name: host_name
          description: Name of the host.
          tests:
            - not_null  
        - name: is_superhost
          tests:
            - accepted_values:
                values: ['Yes', 'No', 'Unknown']
    - name: dim_listings_w_hosts
      description: Verifies that the row count in this model matches the source Airbnb raw_listings table.
      tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'raw_listings')
      columns:
        - name: price
          description: Ensures most prices fall within a reasonable range ($50-$500), warns for outliers, and that price is a number type. 
          tests:
            - dbt_expectations.expect_column_values_to_be_of_type:
                column_type: number    
            - dbt_expectations.expect_column_quantile_values_to_be_between:
                quantile: .99
                min_value: 50
                max_value: 500
            - dbt_expectations.expect_column_max_to_be_between:
                max_value: 5000
                config:
                  severity: warn
    - name: fct_reviews
      description: Cleaned table which contains reviews
      columns:
        - name: listing_id
          description: The id of the listing References the listings table
          tests:
            - relationships:
                to: ref('dim_listings_cleaned')
                field: listing_id
        - name: reviewer_name
          description: The name of the reviewer is not_null
          tests:
            - not_null
        - name: review_sentiment
          description: The sentiment of the review is in the accepted values
          tests:
            - accepted_values:
                values: ['positive', 'negative', 'neutral']